### ISSUE TITLE
Class Diagram

### ISSUE THREAD

**Issue by AVMartin14** [holidaygarrison/Group3#16]
Class diagram for the proposed system & should be consistent with the SRS.

**Comment by holidaygarrison** [comment]
<img width="591" alt="Capture" src="https://user-images.githubusercontent.com/60896633/191633094-e21f40d5-5f8c-4766-8630-9929649fb3ce.PNG">

Version 1.0 of the class Diagram completed

**Comment by AVMartin14** [comment]
This is our class diagram as of now.
