### ISSUE TITLE
Sequence Diagram For Each User Story

### ISSUE THREAD

**Issue by AVMartin14** [holidaygarrison/Group3#17]
Sequence diagram for each one of the user stories & consistent.

**Comment by AVMartin14** [comment]
Created the sequence diagram for the first user story.
<img width="601" alt="Screen Shot 2022-09-26 at 5 22 45 PM" src="https://user-images.githubusercontent.com/104539959/192391093-c0b3309c-f980-452e-80f1-6af782845717.png">

**Comment by tiamalley** [comment]
Created the sequence diagram for the fourth user story.
![image](https://user-images.githubusercontent.com/104528224/192426243-bb4b2a5f-cffa-4cdb-ba89-ba10889ccc24.png)

**Comment by AVMartin14** [comment]
Created the sequence diagram for the second user story.
<img width="678" alt="Screen Shot 2022-09-28 at 3 11 09 PM" src="https://user-images.githubusercontent.com/104539959/192879214-9250a225-d0e0-4eea-b96b-cfc88fda871b.png">

**Comment by AVMartin14** [comment]
Created the sequence diagram for the fifth user story.
<img width="678" alt="Screen Shot 2022-09-28 at 3 28 26 PM" src="https://user-images.githubusercontent.com/104539959/192882268-0c81920c-1830-49ca-849b-be0840957998.png">

**Comment by holidaygarrison** [comment]
Sequence Diagram for the 5th User Story:
![image](https://user-images.githubusercontent.com/60896633/194185275-7dafd3a9-8aa8-4cd0-9255-3062992a1553.png)

**Comment by AVMartin14** [comment]
<img width="579" alt="Screen Shot 2022-10-05 at 7 16 28 PM" src="https://user-images.githubusercontent.com/104539959/194186275-5407a467-f61e-47f8-b1f4-9d2a03433ac9.png">

**Comment by AVMartin14** [comment]
We made sequence diagrams for user stories 1-5. We updated user story 3 and 5 to match what we have currently done for the website.
