### ISSUE TITLE
Fatal Error when sharing posts with apostrophe in comment

### ISSUE THREAD

**Issue by Giza-Deminuit** [holidaygarrison/Group3#56]
When a user attempts to share a post and includes a comment on the post they're about to share that has an apostrophe in it, it causes the following fatal error:

> Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 't see any bread. Where is it?', NULL, '18')' at line 1 in C:\xampp\htdocs\SWE\Group3\lib\posts_class.php:193 Stack trace: #0 C:\xampp\htdocs\SWE\Group3\lib\posts_class.php(193): mysqli->query('INSERT INTO pos...') #1 C:\xampp\htdocs\SWE\Group3\SharePostPro.php(16): Posts::SharePost('Giza', '18', 'I don't see any...') #2 {main} thrown in C:\xampp\htdocs\SWE\Group3\lib\posts_class.php on line 193

**Comment by holidaygarrison** [comment]
Resolved with Commit #64
