### ISSUE TITLE
Fatal error when including an apostrophe in a comment on a post

### ISSUE THREAD

**Issue by Giza-Deminuit** [holidaygarrison/Group3#57]
When a user attempts to comment on a post and includes an apostrophe in the comment, it causes the following fatal error:

> Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'f')' at line 1 in C:\xampp\htdocs\SWE\Group3\lib\posts_class.php:209 Stack trace: #0 C:\xampp\htdocs\SWE\Group3\lib\posts_class.php(209): mysqli->query('INSERT INTO com...') #1 C:\xampp\htdocs\SWE\Group3\PostComment.php(17): Posts::MakeComment('Giza', '21', 'pos ' f') #2 {main} thrown in C:\xampp\htdocs\SWE\Group3\lib\posts_class.php on line 209

**Comment by holidaygarrison** [comment]
Resolved with Commit #64
