### ISSUE TITLE
Fatal error when making post with an apostrophe in the comment

### ISSUE THREAD

**Issue by Giza-Deminuit** [holidaygarrison/Group3#58]
When a user attempts to make a post and includes a comment on the post that has an apostrophe in it, it causes the following fatal error:

> Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''', NULL)' at line 1 in C:\xampp\htdocs\SWE\Group3\lib\posts_class.php:15 Stack trace: #0 C:\xampp\htdocs\SWE\Group3\lib\posts_class.php(15): mysqli->query('INSERT INTO pos...') #1 C:\xampp\htdocs\SWE\Group3\CreatePostPro.php(21): Posts::CreatePost('Giza', ''', NULL) #2 {main} thrown in C:\xampp\htdocs\SWE\Group3\lib\posts_class.php on line 15

**Comment by holidaygarrison** [comment]
Resolved with Commit #64
