### ISSUE TITLE
Website Design Plan

### ISSUE THREAD

**Issue by Giza-Deminuit** [holidaygarrison/Group3#9]
We need to plan the design of the user-facing side of our site. This could be done as a sketch, or with software.

**Comment by Giza-Deminuit** [comment]
Here's a rough idea of what the home/timeline could look like: 

![Homepage sketch](https://user-images.githubusercontent.com/67812331/192377237-dafa9361-e25d-4583-aed5-2b407ea4b2fc.jpg)

**Comment by AVMartin14** [comment]
For the edit profile, I was think we could just label what the user can change and add a change button to each one similar to this:

<img width="360" alt="Screen Shot 2022-09-26 at 3 44 57 PM" src="https://user-images.githubusercontent.com/104539959/192377200-e99b4446-b127-4b8d-906c-8a96c1f01ffc.png">

For the post popup, I thought we could do ours similar to Facebooks and just make it a box to drag and drop, attach, or find an image or gif for the meme post and then possibly a text area where the user could input a caption:
<img width="230" alt="Screen Shot 2022-09-26 at 3 45 08 PM" src="https://user-images.githubusercontent.com/104539959/192377519-0c7cf268-c83d-4e9e-84c3-4d3ab1a382f5.png">

**Comment by tiamalley** [comment]
Here is the profile page idea.

![image](https://user-images.githubusercontent.com/104528224/192378431-f9f9e47f-312d-4a73-94c6-3ca6e298811a.png)
![image](https://user-images.githubusercontent.com/104528224/192378513-d02d0154-26f2-4e2e-9ab6-ae8de06e48ea.png)

**Comment by Giza-Deminuit** [comment]
Design complete.
